### ISSUE TITLE
#id scroll reveals the top-navigation-bar 

### ISSUE THREAD

**Issue by mayankdixit** [weaintplastic/jquery-unveiled-navigation#3]
`something.com/about#somelink`
reveals top-navigation-bar

**Comment by weaintplastic** [comment]
Since jumping to a page internal link will trigger a scroll event, the navigation bar will be unveiled if the scroll direction is from bottom to top or if the page scroll position is at the very end of the document. 

As of Version 0.4.1 you'll be able to disable and enable the plugin. This might help
